version: "3.9"

services:
  rs_extractor:
    image: "realmsense/extractor"
    build:
      context: ./container_data/rotmg-extractor
      dockerfile: Dockerfile
    container_name: "rs-extractor"
    restart: unless-stopped
    shm_size: "2gb"
    volumes:
      - ./container_data/rotmg-extractor:/usr/src/app
      - ./container_data/ida_shared:/usr/src/ida

  rs_extractor_ida:
    image: "realmsense/ida-wine"
    build:
      context: ./container_data/ida-docker-wine/ida-docker
      dockerfile: Dockerfile
    container_name: "rs-extractor-ida"
    restart: unless-stopped
    volumes:
      - ./container_data/ida_shared:/root/ida
      - ./container_data/ida-docker-wine/ida-docker/server:/root/server

  rs_extractor_nginx:
    image: "nginx:1.21.1"
    container_name: "rs-extractor-nginx"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.rs-extractor.rule=Host(`${EXTRACTOR_URL}`)"
      - "traefik.http.routers.rs-extractor.entrypoints=websecure"
      - "traefik.http.routers.rs-extractor.tls.certresolver=dnsresolver"

    volumes:
      - ./container_data/rotmg-extractor/output/publish:/usr/share/nginx
      - ./container_data/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik

networks:
  traefik:
    external: true
