version: "3.9"

services:
  
  rs_api:
    build:
      context: ./container_data/api
      dockerfile: Dockerfile
    container_name: "rs-api"
    restart: unless-stopped
    volumes:
      - ./container_data/persist/builds_uploads:/usr/src/app/build_uploads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.rs-api.rule=Host(`${API_URL}`)"
      - "traefik.http.routers.rs-api.entrypoints=websecure"
      - "traefik.http.routers.rs-api.tls.certresolver=dnsresolver"
      - "traefik.http.services.rs-api.loadbalancer.server.port=3000"
    networks:
      - traefik
      - realmsense

networks:
  traefik:
    external: true
  realmsense:
    external: true
